### ISSUE TITLE
Extensions stops page content from beeing reorderd in backend per drag & drop (Typo3 11.5.2)

### ISSUE THREAD

**Issue by kosimas** [IchHabRecht/content_defender#91]
Reordering page content is not working with ichhabrecht/content-defender:^3.2 and Typo3 ^11.5.0.

`"Argument 2 passed to TYPO3\CMS\Backend\Configuration\TypoScript\ConditionMatching\ConditionMatcher::getPageIdByRecord() must be of the type int, array given, called in /var/www/html/public/typo3/sysext/backend/Classes/Configuration/TypoScript/ConditionMatching/ConditionMatcher.php on line 120"`

**Comment by Schweriner** [comment]
I can confirm this issue.

**Comment by kosimas** [comment]
I debugged this error and this can possibly be a typo3 bug and not a bug in this extension.

In this line $target is an array and has to be an int.
https://github.com/TYPO3/typo3/blob/920e1ef40f392d7aa40becc4f0f7aa9103df03a6/typo3/sysext/backend/Classes/Configuration/TypoScript/ConditionMatching/ConditionMatcher.php#L120

You can change this line to 
```php
$pageId = $this->getPageIdByRecord($table, $target['target'], true);
```
After that change, everything seems to work as excpected. But changing the Typo3 core is never a good idea.
Maybe @IchHabRecht can assess that better.

**Comment by Schweriner** [comment]
I did the same as a hotfix but the occur does not occur when not using content_defender... so maybe the cmdMap is not valid with v11?

**Comment by IchHabRecht** [comment]
Hi @kosimas,

Thank you for your issue report. As you already found, it is not related to content_defender itself but to a TYPO3 core issue. There is nothing I can do extension wise as the extension neither generates the cmdMap nor triggers the ConditionMatcher initialization itself. But this problem is triggered as content_defender needs to initalize an instance of the BackendLayout to resolve its configuration for proper record validation. I can push a bugfix solution for the core but it needs a new TYPO3 release before the issue gets resolved.

**Comment by IchHabRecht** [comment]
I found a way to resolve the core issue within the extension. The new release 3.2.1 should fix the problem.

**Comment by kevin-appelt** [comment]
I updated my composer packages, cleared all caches (TYPO3 and Browser) but the issue isn't solved for me with the release. I still get this error:
`Argument 2 passed to TYPO3\CMS\Backend\Configuration\TypoScript\ConditionMatching\ConditionMatcher::getPageIdByRecord() must be of the type int, array given, called in [...]/typo3/sysext/backend/Classes/Configuration/TypoScript/ConditionMatching/ConditionMatcher.php on line 120`

**Can someone confirm, if the issue is or isn't resolved?**

---

@IchHabRecht
>I can push a bugfix solution for the core but it needs a new TYPO3 release before the issue gets resolved.

Is there a patch pending? Would be great to see this issue solved core wise in the next release (which is scheduled for November 16th, 2021)

**Comment by IchHabRecht** [comment]
Hi @kevin-appelt,

I can confirm that the problem is resolved with the latest release of content_defender. After some more investigation I found out that drag&drop is broken core wise if you disable the "hash" cash (e.g. use NullBackend). So in your case the drag&drop shouldn't work even if content_defender is disabled. Please give some feedback if is broken without content_defender as well.

**Comment by kevin-appelt** [comment]
@IchHabRecht I can confirm that the issue is still present if content_defender is disabled/removed (with NullBackend as cache).
Furthermore i can confirm that the issue is gone if I change to not use NullBackend (no matter if with content_defender active/present or not.
